import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    backToBrands: "Back to Brands",
    backToModels: "Back to Models",
    searchPlaceholder: "Search models...",
    typeAll: "All",
    typeElectric: "Electric",
    typeAcoustic: "Acoustic",
    typeBass: "Bass",
    modelsTitle: "Models",
    loading: "Loading...",
    errorLoading: "Error loading data",
    error: "An error occurred",
    Specification: "Specification",
    "Who plays it?": "Who plays it?",
    noMusiciansFound: "No musicians found.",
    prev: "Prev",
    next: "Next",
    store: "Store",
    collections: "Collections",
    support: "Support",
    terms: "Terms",
    privacy: "Privacy Policy",
    copyright: "Copyright",
    followUs: "Follow Us",
    pages: "Pages",
    product: "Product",
    footerLocation: "San Francisco",
    footerEmail: "Enquiry@VibeStrings.com",
    footerCopy: "© 2022 Copyright. VibeStrings",
    checkOutSelection: "Check out the",
    filterByType: "Filter by type",
    all: "All",
    "Body Wood": "Body Wood",
    "Neck Wood": "Neck Wood",
    "Fingerboard Wood": "Fingerboard Wood",
    Pickups: "Pickups",
    Tuners: "Tuners",
    "Scale Length": "Scale Length",
    Bridge: "Bridge",
    showingResults: "Showing {count} results from {total}",
    playLike: "Play like a",
rockStar: "Rock star",
brandDescription: "With a legacy dating back to the 1950s, {brand} blends expert craftsmanship with cutting-edge innovation to deliver guitars that inspire creativity and elevate your performance. Trusted by top artists worldwide, {brand} guitars are built to play fast, sound bold, and stand out on any stage.",
"browseTopQuality": "Browse top quality",
  "guitars": "Guitars",
  "online": "online",
  "exploreCollections": "Explore 50k+ latest collections of branded guitars",
  "withVibeStrings": "online with VibeStrings.",
  "featuringThe": "Featuring the",
  "bestBrands": "Best Brands",
  "selectYourBrand": "Select your preferred brand and explore our exquisite collection.",
  "whyTry": "Why try",
"smoothBrowsing": "Smooth Browsing",
  "smoothBrowsingDescLine1": "Lorem ipsum dolor sit amet,",
  "smoothBrowsingDescLine2": "consectetur adipiscing elit.",
  "Easy Delivery": "Easy Delivery",
"Easy Delivery Description Line1": "Fast and safe shipping",
"Easy Delivery Description Line2": "right to your doorstep",
"Swift Payments": "Swift Payments",
"Swift Payments Description Line1": "Secure and quick payment",
"Swift Payments Description Line2": "with multiple options",
"heroFinalTitleLine1": "Browse and buy your",
"heroFinalTitleHighlight": "favorite guitars",
"heroFinalTitleLine2": "with",




  },
  mk: {
    backToBrands: "Назад кон брендови",
    backToModels: "Назад кон модели",
    searchPlaceholder: "Пребарувај модели...",
    typeAll: "Сите",
    typeElectric: "Електрични",
    typeAcoustic: "Акустични",
    typeBass: "Бас",
    modelsTitle: "Модели",
    loading: "Се вчитува...",
    errorLoading: "Грешка при вчитување",
    error: "Се појави грешка",
    Specification: "Спецификации",
    "Who plays it?": "Кој ја користи?",
    noMusiciansFound: "Нема пронајдени музичари.",
    prev: "Претходно",
    next: "Следно",
    store: "Продавница",
    collections: "Колекции",
    support: "Поддршка",
    terms: "Услови",
    privacy: "Политика за приватност",
    copyright: "Авторски права",
    followUs: "Следете не",
    pages: "Страници",
    product: "Производ",
    footerLocation: "Сан Франциско",
    footerEmail: "Прашување@VibeStrings.com",
    footerCopy: "© 2022 Авторски права. VibeStrings",
    checkOutSelection: "Разгледај ја",
    filterByType: "Филтрирај по тип",
    all: "Сите",
    "Body Wood": "Дрво на тело",
    "Neck Wood": "Дрво на врат",
    "Fingerboard Wood": "Дрво на фретборд",
    Pickups: "Пикап",
    Tuners: "Штимерки",
    "Scale Length": "Должина на скала",
    Bridge: "Мост",
    showingResults: "Се прикажуваат {count} резултати од {total}",
    playLike: "Свири како",
rockStar: "Рок ѕвезда",
brandDescription: "Со традиција што датира од 1950-тите, {brand} комбинира извонредна изработка со најсовремени иновации за да создаде гитари што инспирираат креативност и ја унапредуваат твојата изведба. Доверени од најдобрите уметници низ светот, гитарите на {brand} се создадени за брзо свирење, моќен звук и впечатлив изглед на секоја сцена.",
"browseTopQuality": "Прелистај гитари од највисок квалитет",
  "guitars": "Гитари",
  "online": "онлајн",
  "exploreCollections": "Истражи 50.000+ најнови колекции од брендирани гитари",
  "withVibeStrings": "онлајн со VibeStrings.",
   "featuringThe": "Претставуваме ги",
  "bestBrands": "најдобрите брендови",
  "selectYourBrand": "Изберете го вашиот омилен бренд и истражете ја нашата извонредна колекција.",
  "whyTry": "Зошто да пробате",
  "smoothBrowsing": "Мазно прелистување",
  "smoothBrowsingDescLine1": "Lorem ipsum dolor sit amet,",
  "smoothBrowsingDescLine2": "consectetur adipiscing elit.",
  "Easy Delivery": "Лесна испорака",
"Easy Delivery Description Line1": "Брза и безбедна испорака",
"Easy Delivery Description Line2": "директно до вашиот дом",
"Swift Payments": "Брзи плаќања",
"Swift Payments Description Line1": "Безбедно и брзо плаќање",
"Swift Payments Description Line2": "со повеќе опции",
"heroFinalTitleLine1": "Разгледај и купи ја твојата",
"heroFinalTitleHighlight": "омилена гитара",
"heroFinalTitleLine2": "со",


  },
  sq: {
    backToBrands: "Kthehu tek markat",
    backToModels: "Kthehu tek modelet",
    searchPlaceholder: "Kërko modele...",
    typeAll: "Të gjitha",
    typeElectric: "Elektrike",
    typeAcoustic: "Akustike",
    typeBass: "Bas",
    modelsTitle: "Modelet",
    loading: "Duke ngarkuar...",
    errorLoading: "Gabim gjatë ngarkimit",
    error: "Ndodhi një gabim",
    Specification: "Specifikimet",
    "Who plays it?": "Kush e përdor?",
    noMusiciansFound: "Nuk u gjetën muzikantë.",
    prev: "Para",
    next: "Tjetër",
    store: "Dyqan",
    collections: "Koleksione",
    support: "Mbështetje",
    terms: "Kushtet",
    privacy: "Politika e privatësisë",
    copyright: "E drejta e autorit",
    followUs: "Na ndiqni",
    pages: "Faqet",
    product: "Produkti",
    footerLocation: "San Francisko",
    footerEmail: "Pyetje@VibeStrings.com",
    footerCopy: "© 2022 E drejta e autorit. VibeStrings",
    checkOutSelection: "Shikoni",
    filterByType: "Filtro sipas llojit",
    all: "Të gjitha",
    "Body Wood": "Dru i trupit",
    "Neck Wood": "Dru i qafës",
    "Fingerboard Wood": "Dru i tastierës",
    Pickups: "Pickups",
    Tuners: "Stabilizuesit",
    "Scale Length": "Gjatësia e diapazonit",
    Bridge: "Ura",
    showingResults: "Duke treguar {count} rezultate nga {total}",
    playLike: "Luaj si një",
rockStar: "Yll Rock-u",
brandDescription: "Me një trashëgimi që daton që nga vitet 1950, {brand} kombinon mjeshtëri të shkëlqyer me inovacion të avancuar për të krijuar kitarra që frymëzojnë krijimtari dhe përmirësojnë performancën tënde. Të besuara nga artistët më të mirë në botë, kitarra të {brand} janë ndërtuar për të luajtur shpejt, për të tingëlluar fuqishëm dhe për të dalë në pah në çdo skenë.",
"browseTopQuality": "Shfleto kitarat me cilësi të lartë",
"guitars": "Kitarat",
"online": "online",
"exploreCollections": "Eksploro 50.000+ koleksione të fundit të kitarave me marka",
"withVibeStrings": "online me VibeStrings.",
"featuringThe": "Prezantimi i",
  "bestBrands": "markave më të mira",
  "selectYourBrand": "Zgjidhni markën tuaj të preferuar dhe eksploroni koleksionin tonë të jashtëzakonshëm.",
  "whyTry": "Pse të provoni",
  "smoothBrowsing": "Shfletim i lehtë",
  "smoothBrowsingDescLine1": "Lorem ipsum dolor sit amet,",
  "smoothBrowsingDescLine2": "consectetur adipiscing elit.",
  "Easy Delivery": "Dërgesë e lehtë",
"Easy Delivery Description Line1": "Transport i shpejtë dhe i sigurt",
"Easy Delivery Description Line2": "direkt te dera juaj",
"Swift Payments": "Pagesa të shpejta",
"Swift Payments Description Line1": "Pagesa të sigurta dhe të shpejta",
"Swift Payments Description Line2": "me shumë opsione",
"heroFinalTitleLine1": "Shfleto dhe bli",
"heroFinalTitleHighlight": "kitarat e tua të preferuara",
"heroFinalTitleLine2": "me",


  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key, vars = {}) => {
    let str = translations[language][key] || key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(`{${k}}`, v);
    });
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
